package entities;
// Generated Nov 20, 2017 1:22:37 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AnomaliaHistory generated by hbm2java
 */
@Entity
@Table(name = "anomalia_history", catalog = "rilasci_DB")
public class AnomaliaHistory implements java.io.Serializable {

	private Integer id;
	private Integer codAnomalia;
	private Integer codStatus;
	private Date dataUpdate;
	private Integer codAuthor;

	public AnomaliaHistory() {
	}

	public AnomaliaHistory(Integer codAnomalia, Integer codStatus, Date dataUpdate, Integer codAuthor) {
		this.codAnomalia = codAnomalia;
		this.codStatus = codStatus;
		this.dataUpdate = dataUpdate;
		this.codAuthor = codAuthor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cod_anomalia")
	public Integer getCodAnomalia() {
		return this.codAnomalia;
	}

	public void setCodAnomalia(Integer codAnomalia) {
		this.codAnomalia = codAnomalia;
	}

	@Column(name = "cod_status")
	public Integer getCodStatus() {
		return this.codStatus;
	}

	public void setCodStatus(Integer codStatus) {
		this.codStatus = codStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_update", length = 19)
	public Date getDataUpdate() {
		return this.dataUpdate;
	}

	public void setDataUpdate(Date dataUpdate) {
		this.dataUpdate = dataUpdate;
	}

	@Column(name = "cod_author")
	public Integer getCodAuthor() {
		return this.codAuthor;
	}

	public void setCodAuthor(Integer codAuthor) {
		this.codAuthor = codAuthor;
	}

}
