package entities;
// Generated Nov 20, 2017 1:22:37 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Assignee generated by hbm2java
 */
@Entity
@Table(name = "assignee", catalog = "rilasci_DB")
public class Assignee implements java.io.Serializable {

	private AssigneeId id;
	private Mev releaseIt;
	private TipoItem tipoItem;
	private User user;

	public Assignee() {
	}

	public Assignee(AssigneeId id, User user) {
		this.id = id;
		this.user = user;
	}

	public Assignee(AssigneeId id, Mev releaseIt, TipoItem tipoItem, User user) {
		this.id = id;
		this.releaseIt = releaseIt;
		this.tipoItem = tipoItem;
		this.user = user;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codIdUser", column = @Column(name = "cod_id_user", nullable = false)),
			@AttributeOverride(name = "codIdPolarion", column = @Column(name = "cod_id_polarion", nullable = false, length = 45)) })
	public AssigneeId getId() {
		return this.id;
	}

	public void setId(AssigneeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_id")
	public Mev getReleaseIt() {
		return this.releaseIt;
	}

	public void setReleaseIt(Mev releaseIt) {
		this.releaseIt = releaseIt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo")
	public TipoItem getTipoItem() {
		return this.tipoItem;
	}

	public void setTipoItem(TipoItem tipoItem) {
		this.tipoItem = tipoItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_id_user", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
