package entities;
// Generated Nov 20, 2017 1:22:37 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Defect generated by hbm2java
 */
@Entity
@Table(name = "defect", catalog = "rilasci_DB", uniqueConstraints = { @UniqueConstraint(columnNames = "cod_priority"),
		@UniqueConstraint(columnNames = "cod_resolution"), @UniqueConstraint(columnNames = "cod_severity"),
		@UniqueConstraint(columnNames = "defectcol"), @UniqueConstraint(columnNames = "id_polarion") })
public class Defect implements java.io.Serializable {

	private Integer id;
	private Priority priority;
	private Severity severity;
	private Status status;
	private User user;
	private String idPolarion;
	private String titolo;
	private Date dataCreazione;
	private Date dataUpdate;
	private Integer codResolution;
	private String defectcol;
	private Set<DefectHistory> defectHistories = new HashSet<DefectHistory>(0);

	public Defect() {
	}

	public Defect(User user) {
		this.user = user;
	}

	public Defect(Priority priority, Severity severity, Status status, User user, String idPolarion, String titolo,
			Date dataCreazione, Date dataUpdate, Integer codResolution, String defectcol,
			Set<DefectHistory> defectHistories) {
		this.priority = priority;
		this.severity = severity;
		this.status = status;
		this.user = user;
		this.idPolarion = idPolarion;
		this.titolo = titolo;
		this.dataCreazione = dataCreazione;
		this.dataUpdate = dataUpdate;
		this.codResolution = codResolution;
		this.defectcol = defectcol;
		this.defectHistories = defectHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_priority", unique = true)
	public Priority getPriority() {
		return this.priority;
	}

	public void setPriority(Priority priority) {
		this.priority = priority;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_severity", unique = true)
	public Severity getSeverity() {
		return this.severity;
	}

	public void setSeverity(Severity severity) {
		this.severity = severity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_status")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_author", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "id_polarion", unique = true, length = 45)
	public String getIdPolarion() {
		return this.idPolarion;
	}

	public void setIdPolarion(String idPolarion) {
		this.idPolarion = idPolarion;
	}

	@Column(name = "titolo", length = 45)
	public String getTitolo() {
		return this.titolo;
	}

	public void setTitolo(String titolo) {
		this.titolo = titolo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_creazione", length = 19)
	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_update", length = 19)
	public Date getDataUpdate() {
		return this.dataUpdate;
	}

	public void setDataUpdate(Date dataUpdate) {
		this.dataUpdate = dataUpdate;
	}

	@Column(name = "cod_resolution", unique = true)
	public Integer getCodResolution() {
		return this.codResolution;
	}

	public void setCodResolution(Integer codResolution) {
		this.codResolution = codResolution;
	}

	@Column(name = "defectcol", unique = true, length = 45)
	public String getDefectcol() {
		return this.defectcol;
	}

	public void setDefectcol(String defectcol) {
		this.defectcol = defectcol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "defect")
	public Set<DefectHistory> getDefectHistories() {
		return this.defectHistories;
	}

	public void setDefectHistories(Set<DefectHistory> defectHistories) {
		this.defectHistories = defectHistories;
	}

}
