package entities;
// Generated Oct 25, 2017 9:10:32 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Esito generated by hbm2java
 */
@Entity
@Table(name = "esito", catalog = "rilasci_DB")
public class Esito implements java.io.Serializable {

	private int id;
	private String nome;
	private Set<ChecklistTestcase> checklistTestcases = new HashSet<ChecklistTestcase>(0);

	public Esito() {
	}

	public Esito(int id) {
		this.id = id;
	}

	public Esito(int id, String nome, Set<ChecklistTestcase> checklistTestcases) {
		this.id = id;
		this.nome = nome;
		this.checklistTestcases = checklistTestcases;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "esito")
	public Set<ChecklistTestcase> getChecklistTestcases() {
		return this.checklistTestcases;
	}

	public void setChecklistTestcases(Set<ChecklistTestcase> checklistTestcases) {
		this.checklistTestcases = checklistTestcases;
	}

}
