package entities;
// Generated Oct 25, 2017 9:10:32 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resolution generated by hbm2java
 */
@Entity
@Table(name = "resolution", catalog = "rilasci_DB")
public class Resolution implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String polarionName;
	private Set<Taskit> taskits = new HashSet<Taskit>(0);
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<Testcase> testcases = new HashSet<Testcase>(0);
	private Set<Task> tasks = new HashSet<Task>(0);

	public Resolution() {
	}

	public Resolution(String nome, String polarionName, Set<Taskit> taskits, Set<Documento> documentos,
			Set<Testcase> testcases, Set<Task> tasks) {
		this.nome = nome;
		this.polarionName = polarionName;
		this.taskits = taskits;
		this.documentos = documentos;
		this.testcases = testcases;
		this.tasks = tasks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "polarion_name", length = 45)
	public String getPolarionName() {
		return this.polarionName;
	}

	public void setPolarionName(String polarionName) {
		this.polarionName = polarionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resolution")
	public Set<Taskit> getTaskits() {
		return this.taskits;
	}

	public void setTaskits(Set<Taskit> taskits) {
		this.taskits = taskits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resolution")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resolution")
	public Set<Testcase> getTestcases() {
		return this.testcases;
	}

	public void setTestcases(Set<Testcase> testcases) {
		this.testcases = testcases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resolution")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

}
