package entities;
// Generated Nov 20, 2017 1:22:37 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "rilasci_DB")
public class Status implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String polarionName;
	private Set<SupportHistory> supportHistories = new HashSet<SupportHistory>(0);
	private Set<TaskHistory> taskHistories = new HashSet<TaskHistory>(0);
	private Set<ReleaseHistory> releaseHistories = new HashSet<ReleaseHistory>(0);
	private Set<ReleaseitHistory> releaseitHistories = new HashSet<ReleaseitHistory>(0);
	private Set<ProgettoSviluppo> progettoSviluppos = new HashSet<ProgettoSviluppo>(0);
	private Set<DefectHistory> defectHistories = new HashSet<DefectHistory>(0);
	private Set<Taskit> taskits = new HashSet<Taskit>(0);
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<Support> supports = new HashSet<Support>(0);
	private Set<Task> tasks = new HashSet<Task>(0);
	private Set<Anomalia> anomalias = new HashSet<Anomalia>(0);
	private Set<Defect> defects = new HashSet<Defect>(0);
	private Set<AnomaliaAssistenza> anomaliaAssistenzas = new HashSet<AnomaliaAssistenza>(0);
	private Set<Testcase> testcases = new HashSet<Testcase>(0);
	private Set<Mev> mevs = new HashSet<Mev>(0);

	public Status() {
	}

	public Status(String nome, String polarionName, Set<SupportHistory> supportHistories,
			Set<TaskHistory> taskHistories, Set<ReleaseHistory> releaseHistories,
			Set<ReleaseitHistory> releaseitHistories, Set<ProgettoSviluppo> progettoSviluppos,
			Set<DefectHistory> defectHistories, Set<Taskit> taskits, Set<Documento> documentos, Set<Support> supports,
			Set<Task> tasks, Set<Anomalia> anomalias, Set<Defect> defects, Set<AnomaliaAssistenza> anomaliaAssistenzas,
			Set<Testcase> testcases, Set<Mev> mevs) {
		this.nome = nome;
		this.polarionName = polarionName;
		this.supportHistories = supportHistories;
		this.taskHistories = taskHistories;
		this.releaseHistories = releaseHistories;
		this.releaseitHistories = releaseitHistories;
		this.progettoSviluppos = progettoSviluppos;
		this.defectHistories = defectHistories;
		this.taskits = taskits;
		this.documentos = documentos;
		this.supports = supports;
		this.tasks = tasks;
		this.anomalias = anomalias;
		this.defects = defects;
		this.anomaliaAssistenzas = anomaliaAssistenzas;
		this.testcases = testcases;
		this.mevs = mevs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "polarion_name", length = 45)
	public String getPolarionName() {
		return this.polarionName;
	}

	public void setPolarionName(String polarionName) {
		this.polarionName = polarionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<SupportHistory> getSupportHistories() {
		return this.supportHistories;
	}

	public void setSupportHistories(Set<SupportHistory> supportHistories) {
		this.supportHistories = supportHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<TaskHistory> getTaskHistories() {
		return this.taskHistories;
	}

	public void setTaskHistories(Set<TaskHistory> taskHistories) {
		this.taskHistories = taskHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<ReleaseHistory> getReleaseHistories() {
		return this.releaseHistories;
	}

	public void setReleaseHistories(Set<ReleaseHistory> releaseHistories) {
		this.releaseHistories = releaseHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<ReleaseitHistory> getReleaseitHistories() {
		return this.releaseitHistories;
	}

	public void setReleaseitHistories(Set<ReleaseitHistory> releaseitHistories) {
		this.releaseitHistories = releaseitHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<ProgettoSviluppo> getProgettoSviluppos() {
		return this.progettoSviluppos;
	}

	public void setProgettoSviluppos(Set<ProgettoSviluppo> progettoSviluppos) {
		this.progettoSviluppos = progettoSviluppos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<DefectHistory> getDefectHistories() {
		return this.defectHistories;
	}

	public void setDefectHistories(Set<DefectHistory> defectHistories) {
		this.defectHistories = defectHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Taskit> getTaskits() {
		return this.taskits;
	}

	public void setTaskits(Set<Taskit> taskits) {
		this.taskits = taskits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Support> getSupports() {
		return this.supports;
	}

	public void setSupports(Set<Support> supports) {
		this.supports = supports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Anomalia> getAnomalias() {
		return this.anomalias;
	}

	public void setAnomalias(Set<Anomalia> anomalias) {
		this.anomalias = anomalias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Defect> getDefects() {
		return this.defects;
	}

	public void setDefects(Set<Defect> defects) {
		this.defects = defects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<AnomaliaAssistenza> getAnomaliaAssistenzas() {
		return this.anomaliaAssistenzas;
	}

	public void setAnomaliaAssistenzas(Set<AnomaliaAssistenza> anomaliaAssistenzas) {
		this.anomaliaAssistenzas = anomaliaAssistenzas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Testcase> getTestcases() {
		return this.testcases;
	}

	public void setTestcases(Set<Testcase> testcases) {
		this.testcases = testcases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Mev> getMevs() {
		return this.mevs;
	}

	public void setMevs(Set<Mev> mevs) {
		this.mevs = mevs;
	}

}
