package entities;
// Generated Nov 20, 2017 1:22:37 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskItHistory generated by hbm2java
 */
@Entity
@Table(name = "task_it_history", catalog = "rilasci_DB")
public class TaskItHistory implements java.io.Serializable {

	private Integer id;
	private Taskit taskit;
	private User user;
	private Integer codStatus;
	private Date dataUpdate;

	public TaskItHistory() {
	}

	public TaskItHistory(Taskit taskit, User user, Integer codStatus, Date dataUpdate) {
		this.taskit = taskit;
		this.user = user;
		this.codStatus = codStatus;
		this.dataUpdate = dataUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_task_it")
	public Taskit getTaskit() {
		return this.taskit;
	}

	public void setTaskit(Taskit taskit) {
		this.taskit = taskit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_author")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "cod_status")
	public Integer getCodStatus() {
		return this.codStatus;
	}

	public void setCodStatus(Integer codStatus) {
		this.codStatus = codStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_update", length = 19)
	public Date getDataUpdate() {
		return this.dataUpdate;
	}

	public void setDataUpdate(Date dataUpdate) {
		this.dataUpdate = dataUpdate;
	}

}
