package entities;
// Generated Nov 20, 2017 1:22:37 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoItem generated by hbm2java
 */
@Entity
@Table(name = "tipo_item", catalog = "rilasci_DB")
public class TipoItem implements java.io.Serializable {

	private int id;
	private String nome;
	private Set<Assignee> assignees = new HashSet<Assignee>(0);

	public TipoItem() {
	}

	public TipoItem(int id) {
		this.id = id;
	}

	public TipoItem(int id, String nome, Set<Assignee> assignees) {
		this.id = id;
		this.nome = nome;
		this.assignees = assignees;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoItem")
	public Set<Assignee> getAssignees() {
		return this.assignees;
	}

	public void setAssignees(Set<Assignee> assignees) {
		this.assignees = assignees;
	}

}
